-- Joanna Neubauer
-- 2024-10-25
-- Oracle Spatial: Typ SDO_GEOMETRY

-- zad1
---- A
CREATE TABLE FIGURY (
    ID NUMBER(1) PRIMARY KEY,
    KSZTALT MDSYS.SDO_GEOMETRY
);

---- B
INSERT INTO FIGURY VALUES(
    1, 
    SDO_GEOMETRY(2003, NULL, NULL,
        SDO_ELEM_INFO_ARRAY(1,1003,4),
        SDO_ORDINATE_ARRAY(3, 5, 5, 7, 7, 5))
);

INSERT INTO FIGURY VALUES(
    2, 
    SDO_GEOMETRY(2003, NULL, NULL,
        SDO_ELEM_INFO_ARRAY(1, 1003, 3),
        SDO_ORDINATE_ARRAY(1, 1, 5, 5))
);

INSERT INTO FIGURY VALUES(
    3, 
    SDO_GEOMETRY(2002, NULL, NULL,
        SDO_ELEM_INFO_ARRAY(1,4,2, 1,2,1, 5,2,2),
        SDO_ORDINATE_ARRAY(3, 2, 6, 2, 7, 3, 8, 2, 7, 1))
);

---- C
INSERT INTO FIGURY VALUES(
    4, 
    SDO_GEOMETRY(2003, NULL, NULL,
        SDO_ELEM_INFO_ARRAY(1,1003,4),
        SDO_ORDINATE_ARRAY(3, 5, 5, 5, 7, 5))
);

---- D
SELECT ID, SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT,0.01) VALID 
FROM FIGURY;

---- E
DELETE FROM FIGURY
    WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.01) <> 'TRUE';

---- F
COMMIT;
