-- Joanna Neubauer
-- 2024-11-08
-- Oracle Spatial: Przetwarzanie danych

-- zad1
---- A
INSERT INTO USER_SDO_GEOM_METADATA VALUES(
    'FIGURY', 'KSZTALT',
    MDSYS.SDO_DIM_ARRAY(
        -- nazwa wymiaru, wartość wymiaru ograniczająca geometrie z dołu, 
        -- wartość ograniczająca z góry, tolerancja
        MDSYS.SDO_DIM_ELEMENT('X', 0, 10, 0.01),
        MDSYS.SDO_DIM_ELEMENT('Y', 0, 10, 0.01)),
    NULL);

---- B
SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000, 8192, 10, 2, 0) 
FROM DUAL;

---- C
CREATE INDEX FIGURY_IDX ON FIGURY(KSZTALT)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

---- D
SELECT ID FROM FIGURY
WHERE SDO_FILTER(
    KSZTALT, 
    SDO_GEOMETRY(2001, NULL, 
        SDO_POINT_TYPE(3, 3, NULL),
        NULL, NULL)) = 'TRUE';

---- E
SELECT ID FROM FIGURY
WHERE SDO_RELATE(
    KSZTALT, 
    SDO_GEOMETRY(2001, NULL, 
        SDO_POINT_TYPE(3, 3, NULL),
        NULL, NULL),
    'mask=ANYINTERACT') = 'TRUE';


-- zad2
---- A
SELECT 
    C.CITY_NAME AS MIASTO,
    ROUND(SDO_NN_DISTANCE(1), 5) ODL
    FROM MAJOR_CITIES C
    WHERE SDO_NN(
        GEOM, 
        (SELECT GEOM FROM MAJOR_CITIES
            WHERE CITY_NAME='Warsaw'),
        'sdo_num_res=10 unit=km', 1) = 'TRUE'
    AND C.CITY_NAME <> 'Warsaw';

---- B
 SELECT 
    C.CITY_NAME AS MIASTO
    FROM MAJOR_CITIES C
    WHERE SDO_WITHIN_DISTANCE(
        C.GEOM, 
        (SELECT GEOM FROM MAJOR_CITIES
            WHERE CITY_NAME='Warsaw'),
        'distance=100 unit=km') = 'TRUE'
    AND C.CITY_NAME <> 'Warsaw';

---- C
SELECT CB.CNTRY_NAME KRAJ, MC.CITY_NAME MIASTO
    FROM MAJOR_CITIES MC, COUNTRY_BOUNDARIES CB
    WHERE
        SDO_RELATE(MC.GEOM, CB.GEOM, 'mask=INSIDE') = 'TRUE'
    AND CB.CNTRY_NAME = 'Slovakia';

---- D
SELECT CB2.CNTRY_NAME AS PANSTWO, 
    ROUND(SDO_GEOM.SDO_DISTANCE(CB.GEOM, CB2.GEOM, 1, 'unit=km'), 7) AS ODL
    FROM COUNTRY_BOUNDARIES CB, COUNTRY_BOUNDARIES CB2
    WHERE
        SDO_RELATE(CB.GEOM, CB2.GEOM, 'mask=anyinteract') <> 'TRUE'
    AND CB.CNTRY_NAME = 'Poland';

-- zad3
---- A
SELECT CB2.CNTRY_NAME, 
    ROUND(SDO_GEOM.SDO_LENGTH(
        SDO_GEOM.SDO_INTERSECTION(CB.GEOM, CB2.GEOM, 1),
        1, 'unit=km'), 7) AS ODLEGLOSC
    FROM COUNTRY_BOUNDARIES CB, COUNTRY_BOUNDARIES CB2
    WHERE SDO_RELATE(CB.GEOM, CB2.GEOM, 'mask=anyinteract') = 'TRUE'
    AND CB.CNTRY_NAME = 'Poland' AND CB2.CNTRY_NAME <> 'Poland';

---- B
SELECT CB.CNTRY_NAME
    FROM COUNTRY_BOUNDARIES CB
    ORDER BY SDO_GEOM.SDO_AREA(
        CB.GEOM, 1) desc
    FETCH FIRST 1 ROWS ONLY;

---- C
SELECT ROUND(SDO_GEOM.SDO_AREA(SDO_GEOM.SDO_MBR(
    SDO_GEOM.SDO_UNION(
        MC.GEOM, MC2.GEOM, 0.01
        )), 1, 'unit=SQ_KM'), 5) SQ_KM
    FROM MAJOR_CITIES MC, MAJOR_CITIES MC2
    WHERE MC.CITY_NAME = 'Warsaw'
    AND MC2.CITY_NAME = 'Lodz';

---- D
SELECT SDO_GEOM.SDO_UNION(CB.GEOM, MC.GEOM, 0.01).GET_DIMS()
    || SDO_GEOM.SDO_UNION(CB.GEOM, MC.GEOM, 0.01).GET_LRS_DIM()
    || LPAD(SDO_GEOM.SDO_UNION(CB.GEOM, MC.GEOM, 0.01).GET_GTYPE(), 2, '0') AS GTYPE
    FROM COUNTRY_BOUNDARIES CB, MAJOR_CITIES MC
    WHERE CB.CNTRY_NAME = 'Poland'
    AND MC.CITY_NAME = 'Prague';

---- E
SELECT MC.CITY_NAME, CB.CNTRY_NAME
    FROM MAJOR_CITIES MC, COUNTRY_BOUNDARIES CB
    WHERE MC.CNTRY_NAME = CB.CNTRY_NAME
    ORDER BY SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(CB.GEOM, 0.01), MC.GEOM, 1)
    FETCH FIRST 1 ROWS ONLY;

---- F
SELECT NAME,
    SUM(DLUGOSC) AS DLUGOSC
    FROM (SELECT R.NAME, 
        ROUND(SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(CB.GEOM, R.GEOM, 1), 1, 'unit=km'), 7) AS DLUGOSC
        FROM RIVERS R, COUNTRY_BOUNDARIES CB
        WHERE CB.CNTRY_NAME = 'Poland'
        AND SDO_GEOM.SDO_INTERSECTION(CB.GEOM, R.GEOM, 1) IS NOT NULL)
    GROUP BY NAME;