-- Joanna Neubauer
-- 2024-11-22
-- Oracle Spatial: Standard SQL/MM 

-- zad1
---- A
SELECT lpad('-',2*(level-1),'|-') || 
    t.owner ||
    '.' || 
    t.type_name ||
    ' (FINAL:' ||
    t.final ||
    ', INSTANTIABLE:' ||
    t.instantiable||
    ', ATTRIBUTES:'||
    t.attributes||
    ', METHODS:'||
    t.methods||
    ')'
FROM all_types t
start WITH t.type_name = 'ST_GEOMETRY'
connect BY PRIOR t.type_name = t.supertype_name
AND PRIOR t.owner = t.owner;

---- B
select distinct m.method_name
from all_type_methods m
where m.type_name like 'ST_POLYGON'
and m.owner = 'MDSYS'
order by 1;

---- C
CREATE TABLE MYST_MAJOR_CITIES (
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
);

---- D
INSERT INTO MYST_MAJOR_CITIES (
    SELECT MC.FIPS_CNTRY, MC.CITY_NAME, TREAT(ST_POINT(MC.GEOM) AS ST_POINT)
        FROM MAJOR_CITIES MC
);


-- zad2
---- A
INSERT INTO MYST_MAJOR_CITIES VALUES(
    'PL',
    'Szczyrk',
    new ST_POINT(19.036107, 49.718655, 8307)
);


-- zad3
---- A
CREATE TABLE MYST_COUNTRY_BOUNDARIES (
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON
);

---- B
INSERT INTO MYST_COUNTRY_BOUNDARIES (
    SELECT CB.FIPS_CNTRY, CB.CNTRY_NAME, TREAT(ST_MULTIPOLYGON(CB.GEOM) AS ST_MULTIPOLYGON)
        FROM COUNTRY_BOUNDARIES CB
);

---- C
SELECT
    B.STGEOM.ST_GEOMETRYTYPE() AS TYP_OBIEKTU,
    COUNT(*) AS ILE
FROM MYST_COUNTRY_BOUNDARIES B
GROUP BY B.STGEOM.ST_GEOMETRYTYPE();

---- D
SELECT
    B.STGEOM.ST_ISSIMPLE()
FROM MYST_COUNTRY_BOUNDARIES B;


-- zad4
---- A
SELECT
    CB.CNTRY_NAME, COUNT(*)
FROM MYST_COUNTRY_BOUNDARIES CB, MYST_MAJOR_CITIES MC
WHERE MC.STGEOM.ST_WITHIN(CB.STGEOM) = 1
GROUP BY CNTRY_NAME;

---- B
SELECT
    CB.CNTRY_NAME AS A_NAME,
    CB2.CNTRY_NAME AS B_NAME
FROM MYST_COUNTRY_BOUNDARIES CB, MYST_COUNTRY_BOUNDARIES CB2
WHERE CB.STGEOM.ST_TOUCHES(CB2.STGEOM) = 1
    AND CB2.CNTRY_NAME = 'Czech Republic';

---- C
SELECT DISTINCT
    CB.CNTRY_NAME, R.NAME
FROM MYST_COUNTRY_BOUNDARIES CB, RIVERS R
WHERE CB.CNTRY_NAME = 'Czech Republic'
    AND ST_LINESTRING(R.GEOM).ST_INTERSECTS(CB.STGEOM) = 1;

---- D
SELECT 
    TREAT(CB.STGEOM.ST_UNION(CB2.STGEOM) AS ST_POLYGON).ST_AREA() AS POWIERZCHNIA
FROM MYST_COUNTRY_BOUNDARIES CB, MYST_COUNTRY_BOUNDARIES CB2
WHERE CB.CNTRY_NAME = 'Czech Republic'
    AND CB2.CNTRY_NAME = 'Slovakia';

---- E
SELECT 
    CB.STGEOM.ST_GEOMETRYTYPE() AS OBIEKT,
    CB.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(WB.GEOM)).ST_GEOMETRYTYPE() AS WEGRY_BEZ
FROM MYST_COUNTRY_BOUNDARIES CB, WATER_BODIES WB
WHERE CB.CNTRY_NAME = 'Hungary'
    AND WB.NAME = 'Balaton';

-- zad5
---- A
EXPLAIN PLAN FOR
    SELECT COUNT(*)
    FROM MYST_COUNTRY_BOUNDARIES CB, MYST_MAJOR_CITIES MC
    WHERE CB.CNTRY_NAME = 'Poland'
        AND SDO_WITHIN_DISTANCE(MC.STGEOM, CB.STGEOM, 'distance=100 unit=km') = 'TRUE'
    GROUP BY CB.CNTRY_NAME;
    
SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY);

---- B
INSERT INTO USER_SDO_GEOM_METADATA (
    SELECT 'MYST_MAJOR_CITIES', 'STGEOM', ASGM.DIMINFO, ASGM.SRID
    FROM ALL_SDO_GEOM_METADATA  ASGM
    WHERE ASGM.TABLE_NAME = 'MAJOR_CITIES'
);

INSERT INTO USER_SDO_GEOM_METADATA (
    SELECT 'MYST_COUNTRY_BOUNDARIES', 'STGEOM', ASGM.DIMINFO, ASGM.SRID
    FROM ALL_SDO_GEOM_METADATA  ASGM
    WHERE ASGM.TABLE_NAME = 'COUNTRY_BOUNDARIES'
);

---- C
-- DROP INDEX MYST_MAJOR_CITIES_IDX;
-- DROP INDEX MYST_COUNTRY_BOUNDARIES_IDX;
-- SELECT * FROM USER_SDO_GEOM_METADATA;

CREATE INDEX MYST_MAJOR_CITIES_IDX
ON MYST_MAJOR_CITIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

CREATE INDEX MYST_COUNTRY_BOUNDARIES_IDX
ON MYST_COUNTRY_BOUNDARIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

----D
-- index wykorzystywany dla MAJOR_CITIES
EXPLAIN PLAN FOR
    SELECT COUNT(*)
    FROM MYST_COUNTRY_BOUNDARIES CB, MYST_MAJOR_CITIES MC
    WHERE CB.CNTRY_NAME = 'Poland'
        AND SDO_WITHIN_DISTANCE(MC.STGEOM, CB.STGEOM, 'distance=100 unit=km') = 'TRUE'
    GROUP BY CB.CNTRY_NAME;
    
SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY);
