-- Joanna Neubauer
-- 2024-11-29
-- Oracle Spatial: Układy LRS (Linear Referencing System)

-- zad1
---- A
CREATE TABLE A6_LRS (
    GEOM SDO_GEOMETRY
);

---- B
INSERT INTO A6_LRS (
    SELECT SR.GEOM
    FROM STREETS_AND_RAILROADS SR, MAJOR_CITIES MC
    WHERE SDO_RELATE(SR.GEOM, 
        SDO_GEOM.SDO_BUFFER(MC.GEOM, 10, 1, 'unit=km'), 'mask=ANYINTERACT') = 'TRUE'
        AND MC.CITY_NAME = 'Koszalin'
);

---- C
SELECT 
    SDO_GEOM.SDO_LENGTH(SR.GEOM, 1, 'unit=km' ) AS DISTANCE,
    ST_LINESTRING(SR.GEOM).ST_NUMPOINTS() AS ST_NUMPOINTS
FROM A6_LRS SR;

---- D
UPDATE A6_LRS A
    SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(A.GEOM, 0, SDO_LRS.GEOM_SEGMENT_LENGTH(A.GEOM));

---- E
INSERT INTO USER_SDO_GEOM_METADATA VALUES (
    'A6_LRS', 'GEOM', 
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
        MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
        MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ),
        8307
);

---- F
CREATE INDEX A6_LRS_IDX 
ON A6_LRS(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;


-- zad2
---- A
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) AS VALID_500
FROM A6_LRS;

---- B
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) AS END_PT
FROM A6_LRS;

---- C
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) as KM150
FROM A6_LRS;

---- D
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPPED
FROM A6_LRS;

---- E
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(A6.GEOM, MC.GEOM) AS WJAZD_NA_A6
FROM A6_LRS A6, MAJOR_CITIES MC
WHERE MC.CITY_NAME = 'Slupsk';

---- F
SELECT 
    SDO_GEOM.SDO_LENGTH(
        SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50, 200, 50, 'unit=m'),
        1, 'unit=m') AS KOSZT
FROM A6_LRS A6, USER_SDO_GEOM_METADATA M
WHERE M.TABLE_NAME = 'A6_LRS'
    AND M.COLUMN_NAME = 'GEOM';